"""SQLAlchemy models for Issuance Service."""

from datetime import datetime, timezone
from sqlalchemy import Column, String, DateTime, Boolean, JSON, Integer, Table, Index, Text, ForeignKey
from sqlalchemy.orm import registry

mapper_registry = registry()


def utcnow():
    """Helper function for timezone-aware timestamps."""
    return datetime.now(timezone.utc)


# Issuance Transactions table
issuance_transactions_table = Table(
    "issuance_transactions",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("organization_id", String, nullable=False),
    Column("credential_template_id", String, nullable=False),
    Column("applicant_id", String, nullable=True),
    Column("application_id", String, nullable=True),
    Column("subject_did", String, nullable=True),
    Column("status", String, nullable=False, default="pending"),
    Column("pre_auth_code", String, nullable=False, unique=True),
    Column("access_token", String, nullable=True),
    Column("c_nonce", String, nullable=True),
    Column("issuer_profile_id", String, nullable=True),
    Column("issuer_mode", String, nullable=False, default="org_managed"),
    Column("issuer_did_override", String, nullable=True),
    Column("signing_service_id", String, nullable=True),
    Column("delivery_mode", String(40), nullable=False, server_default="wallet_only"),
    Column("claims", JSON, nullable=False, default=dict),
    Column("credential_type", String, nullable=True),
    Column("zk_predicate_claims", JSON, nullable=True, default=list),
    Column("selective_disclosure_claims", JSON, nullable=True, default=list),
    Column("credential_payload_format", String(30), nullable=False, server_default="w3c_vcdm_v2_sd_jwt"),
    Column("wallet_configs", JSON, nullable=True, server_default="[]"),
    Column("created_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("issued_at", DateTime(timezone=True), nullable=True),
    Column("revoked_at", DateTime(timezone=True), nullable=True),
    Column("revocation_reason", String, nullable=True),
    Index("ix_issuance_transactions_organization_id", "organization_id"),
    Index("ix_issuance_transactions_status", "status"),
    Index("ix_issuance_transactions_pre_auth_code", "pre_auth_code"),
    Index("ix_issuance_transactions_applicant_id", "applicant_id"),
    Index("ix_issuance_transactions_application_id", "application_id"),
    Index("ix_issuance_transactions_delivery_mode", "delivery_mode"),
    schema="issuance_service"
)

# Issued Credentials table
issued_credentials_table = Table(
    "issued_credentials",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("transaction_id", String, ForeignKey("issuance_service.issuance_transactions.id", ondelete="CASCADE"), nullable=False),
    Column("organization_id", String, nullable=False),
    Column("credential_template_id", String, nullable=False),
    Column("applicant_id", String, nullable=True),
    Column("subject_did", String, nullable=True),
    Column("issuer_did", String, nullable=True),
    Column("revocation_profile_id", String, nullable=True),
    Column("status_list_entries", JSON, nullable=False, default=list),
    Column("credential_jwt", String, nullable=False),
    Column("credential_hash", String, nullable=False),
    Column("status", String, nullable=False, default="active"),
    Column("status_updated_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("revoked", Boolean, nullable=False, default=False),
    Column("revoked_at", DateTime(timezone=True), nullable=True),
    Column("revocation_reason", String, nullable=True),
    Column("issued_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("expires_at", DateTime(timezone=True), nullable=True),
    Index("ix_issued_credentials_organization_id", "organization_id"),
    Index("ix_issued_credentials_status", "status"),
    Index("ix_issued_credentials_applicant_id", "applicant_id"),
    schema="issuance_service"
)

credential_delivery_records_table = Table(
    "credential_delivery_records",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("credential_id", String, ForeignKey("issuance_service.issued_credentials.id", ondelete="CASCADE"), nullable=False),
    Column("transaction_id", String, ForeignKey("issuance_service.issuance_transactions.id", ondelete="CASCADE"), nullable=False),
    Column("organization_id", String, nullable=False),
    Column("delivery_target", String(40), nullable=False),
    Column("delivery_mode", String(40), nullable=False, server_default="wallet_only"),
    Column("status", String(40), nullable=False, server_default="pending"),
    Column("canvas_account_id", String, nullable=True),
    Column("external_credential_id", String, nullable=True),
    Column("external_issuer_id", String, nullable=True),
    Column("last_error", Text, nullable=True),
    Column("metadata", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("updated_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Index("ix_credential_delivery_records_credential_id", "credential_id"),
    Index("ix_credential_delivery_records_transaction_id", "transaction_id"),
    Index("ix_credential_delivery_records_organization_id", "organization_id"),
    Index("ix_credential_delivery_records_status", "status"),
    Index("ix_credential_delivery_records_delivery_target", "delivery_target"),
    Index("ix_credential_delivery_records_external_credential_id", "external_credential_id"),
    Index("ix_credential_delivery_records_canvas_account_id", "canvas_account_id"),
    schema="issuance_service",
)

evidence_facts_table = Table(
    "evidence_facts",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("organization_id", String, nullable=False),
    Column("application_id", String, ForeignKey("issuance_service.applications.id", ondelete="CASCADE"), nullable=False),
    Column("subject_id", String, nullable=False),
    Column("provider", String(80), nullable=False),
    Column("fact_type", String(160), nullable=False),
    Column("scope", JSON, nullable=False, default=dict),
    Column("assertion", JSON, nullable=False, default=dict),
    Column("verification", JSON, nullable=False, default=dict),
    Column("source", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Index("ix_evidence_facts_organization_id", "organization_id"),
    Index("ix_evidence_facts_application_id", "application_id"),
    Index("ix_evidence_facts_provider", "provider"),
    Index("ix_evidence_facts_fact_type", "fact_type"),
    schema="issuance_service",
)

# Application Templates table
application_templates_table = Table(
    "application_templates",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("organization_id", String, nullable=False),
    Column("name", String, nullable=False),
    Column("description", String, nullable=True),
    Column("credential_template_id", String, nullable=True),
    Column("form_fields", JSON, nullable=False, default=list),
    Column("evidence_requirements", JSON, nullable=False, default=list),
    Column("claim_collection_rules", JSON, nullable=False, default=list),
    Column("required_checks", JSON, nullable=False, default=list),
    Column("approval_strategy", String, nullable=False, default="auto"),
    Column("approval_policy_set_id", String, nullable=True),
    Column("application_validity_days", Integer, nullable=False, default=30),
    Column("ui_config", JSON, nullable=False, default=dict),
    Column("notification_config", JSON, nullable=False, default=dict),
    Column("status", String, nullable=False, default="active"),
    Column("created_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("updated_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Index("ix_application_templates_organization_id", "organization_id"),
    Index("ix_application_templates_status", "status"),
    schema="issuance_service"
)

# Applications table
applications_table = Table(
    "applications",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("organization_id", String, nullable=False),
    Column("application_template_id", String, ForeignKey("issuance_service.application_templates.id", ondelete="CASCADE"), nullable=False),
    Column("applicant_identifier", String, nullable=False),
    Column("form_data", JSON, nullable=False, default=dict),
    Column("submitted_evidence", JSON, nullable=False, default=list),
    Column("integration_context", JSON, nullable=False, default=dict),
    Column("status", String, nullable=False, default="pending"),
    Column("review_notes", String, nullable=True),
    Column("reviewer_id", String, nullable=True),
    Column("rejection_reason", String, nullable=True),
    Column("derived_claims", JSON, nullable=False, default=dict),
    Column("issuance_transaction_id", String, nullable=True),
    Column("credential_id", String, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("updated_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("submitted_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("reviewed_at", DateTime(timezone=True), nullable=True),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Index("ix_applications_organization_id", "organization_id"),
    Index("ix_applications_status", "status"),
    Index("ix_applications_template_id", "application_template_id"),
    Index("ix_applications_applicant_identifier", "applicant_identifier"),
    schema="issuance_service"
)

# Issuance Events table — append-only audit/lifecycle log
physical_document_jobs_table = Table(
    "physical_document_jobs",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("organization_id", String, nullable=False),
    Column("flow_execution_id", String, nullable=False),
    Column("application_id", String, nullable=False, unique=True),
    Column("application_template_id", String, nullable=False),
    Column("credential_template_id", String, nullable=False),
    Column("delivery_destination_profile_id", String(128), nullable=False),
    Column("document_type", String(3), nullable=False),
    Column("country_code", String(3), nullable=False),
    Column("secure_artifact_ciphertext", Text, nullable=False),
    Column("secure_artifact_reference", String(512), nullable=False),
    Column("sod_sha256", String(64), nullable=True),
    Column("bureau_job_id", String(255), nullable=True),
    Column("tracking_number", String(255), nullable=True),
    Column("status", String(40), nullable=False, default="DRAFT"),
    Column("quality_result", JSON, nullable=True),
    Column("error_code", String(128), nullable=True),
    Column("error_message", String(1024), nullable=True),
    Column("submitted_at", DateTime(timezone=True), nullable=True),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("updated_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Index("ix_physical_document_jobs_organization_id", "organization_id"),
    Index("ix_physical_document_jobs_flow_execution_id", "flow_execution_id"),
    Index("ix_physical_document_jobs_status", "status"),
    Index("ix_physical_document_jobs_bureau_job_id", "bureau_job_id"),
    schema="issuance_service",
)

issuance_events_table = Table(
    "issuance_events",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("transaction_id", String, ForeignKey("issuance_service.issuance_transactions.id", ondelete="SET NULL"), nullable=True),
    Column("application_id", String, ForeignKey("issuance_service.applications.id", ondelete="SET NULL"), nullable=True),
    Column("event_type", String, nullable=False),
    Column("metadata", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Index("ix_issuance_events_application_id", "application_id"),
    Index("ix_issuance_events_transaction_id", "transaction_id"),
    Index("ix_issuance_events_event_type", "event_type"),
    schema="issuance_service"
)

# Replay-safe inbound Canvas event receipts
canvas_event_receipts_table = Table(
    "canvas_event_receipts",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("provider_event_id", String, nullable=False),
    Column("organization_id", String, nullable=False),
    Column("credential_template_id", String, nullable=False),
    Column("canvas_account_id", String, nullable=True),
    Column("payload_hash", String, nullable=False),
    Column("issuance_transaction_id", String, ForeignKey("issuance_service.issuance_transactions.id", ondelete="SET NULL"), nullable=True),
    Column("issuance_response", JSON, nullable=False, default=dict),
    Column("status", String, nullable=False, default="processed"),
    Column("error_summary", String, nullable=True),
    Column("first_seen_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("last_seen_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Index("ix_canvas_event_receipts_provider_event_id", "provider_event_id"),
    Index("ix_canvas_event_receipts_organization_id", "organization_id"),
    Index("ux_canvas_event_receipts_account_event", "canvas_account_id", "provider_event_id", unique=True),
    schema="issuance_service"
)

# Authorization Sessions table — OID4VCI authorization code flow (§5)
canvas_platforms_table = Table(
    "canvas_platforms",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("organization_id", String, nullable=False),
    Column("canvas_account_id", String, nullable=False),
    Column("display_name", String, nullable=True),
    Column("canvas_base_url", Text, nullable=True),
    Column("lti_client_id", Text, nullable=True),
    Column("lti_deployment_id", Text, nullable=True),
    Column("lti_issuer", Text, nullable=True),
    Column("lti_jwks_url", Text, nullable=True),
    Column("lti_jwks_json", JSON, nullable=True),
    Column("lti_jwks_fetched_at", DateTime(timezone=True), nullable=True),
    Column("lti_jwks_expires_at", DateTime(timezone=True), nullable=True),
    Column("lti_openid_configuration", JSON, nullable=True),
    Column("enabled", Boolean, nullable=False, default=True),
    Column("created_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("updated_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Index("ix_canvas_platforms_organization_id", "organization_id"),
    Index("ix_canvas_platforms_canvas_account_id", "canvas_account_id"),
    Index("ux_canvas_platforms_org_account", "organization_id", "canvas_account_id", unique=True),
    schema="issuance_service",
)

canvas_program_bindings_table = Table(
    "canvas_program_bindings",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("organization_id", String, nullable=False),
    Column("platform_id", String, ForeignKey("issuance_service.canvas_platforms.id", ondelete="CASCADE"), nullable=False),
    Column("application_template_id", String, nullable=False),
    Column("credential_template_id", String, nullable=False),
    Column("display_name", String, nullable=True),
    Column("flow_mode", String(80), nullable=False, default="elevenid_orchestrated_canvas_evidence"),
    Column("direct_issue_enabled", Boolean, nullable=False, default=False),
    Column("auto_approve_on_evidence", Boolean, nullable=False, default=False),
    Column("evidence_requirements", JSON, nullable=False, default=list),
    Column("canvas_scope", JSON, nullable=False, default=dict),
    Column("delivery_mode", String(40), nullable=False, server_default="wallet_only"),
    Column("issuer_mode", String(40), nullable=False, server_default="org_managed"),
    Column("approval_policy_set_id", String, nullable=True),
    Column("deployment_profile_id", String, nullable=True),
    Column("feature_flags", JSON, nullable=False, default=dict),
    Column("canvas_credentials", JSON, nullable=False, default=dict),
    Column("enabled", Boolean, nullable=False, default=True),
    Column("created_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("updated_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Index("ix_canvas_program_bindings_organization_id", "organization_id"),
    Index("ix_canvas_program_bindings_platform_id", "platform_id"),
    Index("ix_canvas_program_bindings_application_template_id", "application_template_id"),
    Index("ix_canvas_program_bindings_credential_template_id", "credential_template_id"),
    Index("ix_canvas_program_bindings_deployment_profile_id", "deployment_profile_id"),
    schema="issuance_service",
)

organization_integration_secrets_table = Table(
    "organization_integration_secrets",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("organization_id", String, nullable=False),
    Column("name", String(255), nullable=False),
    Column("provider", String(80), nullable=False),
    Column("purpose", String(80), nullable=False, server_default="api_token"),
    Column("encrypted_secret_value", Text, nullable=False),
    Column("secret_hint", String(80), nullable=True),
    Column("metadata", JSON, nullable=False, default=dict),
    Column("enabled", Boolean, nullable=False, default=True),
    Column("created_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("updated_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("last_used_at", DateTime(timezone=True), nullable=True),
    Index("ix_org_integration_secrets_organization_id", "organization_id"),
    Index("ix_org_integration_secrets_provider", "provider"),
    Index("ux_org_integration_secrets_org_provider_name", "organization_id", "provider", "name", unique=True),
    schema="issuance_service",
)

canvas_lti_launch_states_table = Table(
    "canvas_lti_launch_states",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("platform_id", String, ForeignKey("issuance_service.canvas_platforms.id", ondelete="CASCADE"), nullable=False),
    Column("organization_id", String, nullable=False),
    Column("canvas_account_id", String, nullable=False),
    Column("state", String, nullable=False, unique=True),
    Column("nonce", String, nullable=False),
    Column("login_hint", String, nullable=True),
    Column("target_link_uri", String, nullable=True),
    Column("lti_message_hint", String, nullable=True),
    Column("redirect_uri", String, nullable=True),
    Column("status", String, nullable=False, default="pending"),
    Column("metadata", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("consumed_at", DateTime(timezone=True), nullable=True),
    Index("ix_canvas_lti_launch_states_state", "state"),
    Index("ix_canvas_lti_launch_states_platform_id", "platform_id"),
    Index("ix_canvas_lti_launch_states_organization_status", "organization_id", "status"),
    schema="issuance_service"
)

authorization_sessions_table = Table(
    "authorization_sessions",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("code", String, nullable=False, unique=True),
    Column("client_id", String, nullable=False),
    Column("redirect_uri", String, nullable=True),
    Column("scope", String, nullable=True),
    Column("state", String, nullable=True),
    Column("issuer_state", String, nullable=True),
    Column("credential_configuration_ids", JSON, nullable=False, default=list),
    Column("organization_id", String, nullable=True),
    Column("code_challenge", String, nullable=True),
    Column("code_challenge_method", String, nullable=True),
    Column("access_token", String, nullable=True),
    Column("c_nonce", String, nullable=True),
    Column("status", String, nullable=False, default="pending"),
    Column("created_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Index("ix_authorization_sessions_code", "code"),
    Index("ix_authorization_sessions_status", "status"),
    Index("ix_authorization_sessions_issuer_state", "issuer_state"),
    schema="issuance_service"
)

# Issuer Signing Keys table — encrypted Ed25519 JWKs per organization
issuer_signing_keys_table = Table(
    "issuer_signing_keys",
    mapper_registry.metadata,
    Column("id", String, primary_key=True),
    Column("organization_id", String, nullable=False, unique=True),
    Column("issuer_did", String, nullable=False),
    Column("key_algorithm", String, nullable=False, server_default="Ed25519"),
    Column("encrypted_jwk_json", Text, nullable=False),
    Column("public_key_b64", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Column("updated_at", DateTime(timezone=True), nullable=False, default=utcnow),
    Index("ix_issuer_signing_keys_organization_id", "organization_id"),
    schema="issuance_service",
)
