"""Initial issuance schema

Revision ID: 735160618517
Revises: 
Create Date: 2026-02-03 02:25:33.568391+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '735160618517'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuance_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('credential_template_id', sa.String(), nullable=False),
    sa.Column('applicant_id', sa.String(), nullable=True),
    sa.Column('subject_did', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pre_auth_code', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('c_nonce', sa.String(), nullable=True),
    sa.Column('claims', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pre_auth_code'),
    schema='issuance_service'
    )
    op.create_index('ix_issuance_transactions_applicant_id', 'issuance_transactions', ['applicant_id'], unique=False, schema='issuance_service')
    op.create_index('ix_issuance_transactions_organization_id', 'issuance_transactions', ['organization_id'], unique=False, schema='issuance_service')
    op.create_index('ix_issuance_transactions_pre_auth_code', 'issuance_transactions', ['pre_auth_code'], unique=False, schema='issuance_service')
    op.create_index('ix_issuance_transactions_status', 'issuance_transactions', ['status'], unique=False, schema='issuance_service')
    op.create_table('issued_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('credential_template_id', sa.String(), nullable=False),
    sa.Column('applicant_id', sa.String(), nullable=True),
    sa.Column('subject_did', sa.String(), nullable=True),
    sa.Column('credential_jwt', sa.String(), nullable=False),
    sa.Column('credential_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='issuance_service'
    )
    op.create_index('ix_issued_credentials_applicant_id', 'issued_credentials', ['applicant_id'], unique=False, schema='issuance_service')
    op.create_index('ix_issued_credentials_organization_id', 'issued_credentials', ['organization_id'], unique=False, schema='issuance_service')
    op.create_index('ix_issued_credentials_status', 'issued_credentials', ['status'], unique=False, schema='issuance_service')
    op.create_index('ix_issued_credentials_subject_did', 'issued_credentials', ['subject_did'], unique=False, schema='issuance_service')
    op.create_index('ix_issued_credentials_transaction_id', 'issued_credentials', ['transaction_id'], unique=False, schema='issuance_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_issued_credentials_transaction_id', table_name='issued_credentials', schema='issuance_service')
    op.drop_index('ix_issued_credentials_subject_did', table_name='issued_credentials', schema='issuance_service')
    op.drop_index('ix_issued_credentials_status', table_name='issued_credentials', schema='issuance_service')
    op.drop_index('ix_issued_credentials_organization_id', table_name='issued_credentials', schema='issuance_service')
    op.drop_index('ix_issued_credentials_applicant_id', table_name='issued_credentials', schema='issuance_service')
    op.drop_table('issued_credentials', schema='issuance_service')
    op.drop_index('ix_issuance_transactions_status', table_name='issuance_transactions', schema='issuance_service')
    op.drop_index('ix_issuance_transactions_pre_auth_code', table_name='issuance_transactions', schema='issuance_service')
    op.drop_index('ix_issuance_transactions_organization_id', table_name='issuance_transactions', schema='issuance_service')
    op.drop_index('ix_issuance_transactions_applicant_id', table_name='issuance_transactions', schema='issuance_service')
    op.drop_table('issuance_transactions', schema='issuance_service')
    # ### end Alembic commands ###
